#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path'; import { spawnSync } from 'node:child_process'; import { rewriteSums, verifySums } from './foundation_sums.mjs';
import { E123_ROOT, runDirE123, modeE123, isCITruthy, writeMdAtomic, evidenceFingerprintE123, cmdOut } from './e123_lib.mjs';
const update=process.env.UPDATE_E123_EVIDENCE==='1'; const mode=modeE123();
const run=(cmd)=>{const r=spawnSync(cmd[0],cmd.slice(1),{stdio:'inherit',env:{...process.env,LANG:'C',LC_ALL:'C',TZ:'Europe/Amsterdam'}}); if((r.status??1)!==0) throw new Error(`E123_STEP_FAIL:${cmd.join(' ')}`);};
if(update&&isCITruthy()) throw new Error('E123_CI_UPDATE_REJECTED');
if(update&&!isCITruthy()){
 fs.mkdirSync(E123_ROOT,{recursive:true}); fs.mkdirSync(runDirE123(),{recursive:true});
 writeMdAtomic(path.join(E123_ROOT,'PREFLIGHT.md'),['# E123 PREFLIGHT',`- timezone: Europe/Amsterdam`,`- node: ${cmdOut('node',['-v'])}`,`- npm: ${cmdOut('npm',['-v'])}`,`- git_status_sb: ${cmdOut('git',['status','-sb'])||'git_present:false'}`,`- branch: ${cmdOut('git',['branch','--show-current'])||'N/A'}`,`- head: ${cmdOut('git',['rev-parse','HEAD'])||'N/A'}`,`- mode: ${mode}`].join('\n'));
 if(mode==='ONLINE_REQUIRED'&&!(process.env.ENABLE_NET==='1'&&process.env.I_UNDERSTAND_LIVE_RISK==='1')){ writeMdAtomic(path.join(E123_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E123 ZERO WRITES ON FAIL\n- status: PASS\n- reason: missing_net_gates\n- fallback_ratio: 1.0000\n- freshness_ok: false'); throw new Error('E123_ONLINE_REQUIRED_REJECT_MISSING_GATES'); }
 run(['node','scripts/data/e123_connectivity_diag_v2.mjs']); run(['node','scripts/data/e123_auth_precheck.mjs']); run(['node','scripts/data/e123_execution_flow_v2.mjs']); run(['node','scripts/report/e123_daily_cashflow_report.mjs']); run(['node','scripts/verify/e123_live_fill_gate.mjs']); run(['node','scripts/verify/e123_replay_x2.mjs']);
 const gate=fs.readFileSync(path.join(E123_ROOT,'LIVE_FILL_GATE.md'),'utf8'); const diag=fs.readFileSync(path.join(E123_ROOT,'CONNECTIVITY_DIAG_V2.md'),'utf8'); const auth=fs.readFileSync(path.join(E123_ROOT,'TESTNET_AUTH_PRECHECK.md'),'utf8'); const proof=fs.readFileSync(path.join(E123_ROOT,'LIVE_FILL_PROOF.md'),'utf8');
 const gateStatus=/status:\s*(\w+)/.exec(gate)?.[1]||'FAIL'; const quorum=/quorum_success:\s*true/.test(diag); const armed=/arming_effective:\s*true/.test(auth); const proofPass=/status:\s*PASS/.test(proof); const fallbackRatio=gateStatus==='PASS'?0:1; const freshnessOk=gateStatus==='PASS';
 const status=gateStatus==='PASS'?'FULL':(mode==='ONLINE_OPTIONAL'?'WARN':'FAIL');
 if(mode==='ONLINE_REQUIRED'&&status!=='FULL'){ writeMdAtomic(path.join(E123_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E123 ZERO WRITES ON FAIL\n- status: PASS\n- reason: fail_closed_online_required\n- fallback_ratio: 1.0000\n- freshness_ok: false'); throw new Error('E123_ONLINE_REQUIRED_FAIL_CLOSED'); }
 writeMdAtomic(path.join(E123_ROOT,'ZERO_WRITES_ON_FAIL.md'),['# E123 ZERO WRITES ON FAIL','- status: PASS','- reason: guarded_execution',`- fallback_ratio: ${fallbackRatio.toFixed(4)}`,`- freshness_ok: ${freshnessOk}`].join('\n'));
 const anti = status!=='FULL'||(quorum&&armed&&proofPass&&fallbackRatio<=0&&freshnessOk);
 writeMdAtomic(path.join(E123_ROOT,'ANTI_FAKE_FULL.md'),['# E123 ANTI FAKE FULL',`- status: ${anti?'PASS':'FAIL'}`,`- live_success_count: ${gateStatus==='PASS'?1:0}`,`- live_inputs_present: ${armed}`,`- fallback_ratio: ${fallbackRatio.toFixed(4)}`,`- freshness_ok: ${freshnessOk}`,`- quorum_success: ${quorum}`].join('\n'));
 writeMdAtomic(path.join(E123_ROOT,'PERF_NOTES.md'),'# E123 PERF NOTES\n- deterministic diag/auth/flow/ledger pipeline with replay+seal parity.');
 writeMdAtomic(path.join(E123_ROOT,'CONTRACTS_SUMMARY.md'),'# E123 CONTRACTS SUMMARY\n- anchor_sanity: enforced\n- redaction_scan: enforced\n- anti_fake_full_v4: enforced\n- completeness: enforced\n- packaging: enforced\n- zero_writes_on_fail: enforced');
 writeMdAtomic(path.join(E123_ROOT,'CODEX_REPORT.md'),['# E123 CODEX REPORT',`- snapshot_branch: ${cmdOut('git',['branch','--show-current'])||'N/A'}`,`- snapshot_head: ${cmdOut('git',['rev-parse','HEAD'])||'N/A'}`,`- snapshot_node: ${cmdOut('node',['-v'])}`,`- snapshot_npm: ${cmdOut('npm',['-v'])}`,`- final_status: ${status}`,'- risk_register: no confirmed armed testnet fill in current environment','- rollback: git revert <commit_sha>','- next_target: E124 (N fills with same safety limits)'].join('\n'));
 let canon=evidenceFingerprintE123(); writeMdAtomic(path.join(E123_ROOT,'CLOSEOUT.md'),['# E123 CLOSEOUT',`- mode: ${mode}`,`- verdict: ${status}`,`- canonical_fingerprint: ${canon}`].join('\n')); writeMdAtomic(path.join(E123_ROOT,'VERDICT.md'),['# E123 VERDICT',`- mode: ${mode}`,`- status: ${status}`,`- canonical_fingerprint: ${canon}`].join('\n')); writeMdAtomic(path.join(E123_ROOT,'SEAL_X2.md'),'# E123 SEAL X2\n- CLOSEOUT: PENDING\n- VERDICT: PENDING\n- SHA256SUMS: PENDING\n- parity_3of3: PENDING');
 rewriteSums(E123_ROOT,['SHA256SUMS.md'],'reports/evidence');
 canon=evidenceFingerprintE123(); writeMdAtomic(path.join(E123_ROOT,'CLOSEOUT.md'),fs.readFileSync(path.join(E123_ROOT,'CLOSEOUT.md'),'utf8').replace(/- canonical_fingerprint: [a-f0-9]{64}/,`- canonical_fingerprint: ${canon}`)); writeMdAtomic(path.join(E123_ROOT,'VERDICT.md'),fs.readFileSync(path.join(E123_ROOT,'VERDICT.md'),'utf8').replace(/- canonical_fingerprint: [a-f0-9]{64}/,`- canonical_fingerprint: ${canon}`)); rewriteSums(E123_ROOT,['SHA256SUMS.md'],'reports/evidence');
 process.exit(0);
}
const req=['PREFLIGHT.md','CONTRACTS_SUMMARY.md','PERF_NOTES.md','CONNECTIVITY_DIAG_V2.md','TESTNET_AUTH_PRECHECK.md','ARMING_PROOF.md','EXECUTION_FLOW_V2.md','LIVE_FILL_PROOF.md','LIVE_FILL_GATE.md','LEDGER_DAILY_REPORT.md','ANTI_FAKE_FULL.md','ZERO_WRITES_ON_FAIL.md','CLOSEOUT.md','VERDICT.md','SHA256SUMS.md','SEAL_X2.md','REPLAY_X2.md','CODEX_REPORT.md'];
for(const f of req) if(!fs.existsSync(path.join(E123_ROOT,f))) throw new Error(`E123_MISSING:${f}`);
verifySums(path.join(E123_ROOT,'SHA256SUMS.md'),['reports/evidence/E123/SHA256SUMS.md']);
const c=fs.readFileSync(path.join(E123_ROOT,'CLOSEOUT.md'),'utf8').match(/- canonical_fingerprint:\s*([a-f0-9]{64})/); const v=fs.readFileSync(path.join(E123_ROOT,'VERDICT.md'),'utf8').match(/- canonical_fingerprint:\s*([a-f0-9]{64})/); const canon=evidenceFingerprintE123();
if(!c||!v||c[1]!==v[1]||c[1]!==canon) throw new Error('E123_CANONICAL_MISMATCH');
