#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path'; import { spawnSync } from 'node:child_process'; import { rewriteSums, verifySums } from './foundation_sums.mjs';
import { E124_ROOT, runDirE124, modeE124, isCITruthy, writeMdAtomic, evidenceFingerprintE124, cmdOut } from './e124_lib.mjs';
const update=process.env.UPDATE_E124_EVIDENCE==='1'; const mode=modeE124(); const run=(cmd)=>{const r=spawnSync(cmd[0],cmd.slice(1),{stdio:'inherit',env:{...process.env,LANG:'C',LC_ALL:'C',TZ:'Europe/Amsterdam'}}); if((r.status??1)!==0) throw new Error(`E124_STEP_FAIL:${cmd.join(' ')}`);};
if(update&&isCITruthy()) throw new Error('E124_CI_UPDATE_REJECTED');
if(update&&!isCITruthy()){
 fs.mkdirSync(E124_ROOT,{recursive:true}); fs.mkdirSync(runDirE124(),{recursive:true});
 writeMdAtomic(path.join(E124_ROOT,'PREFLIGHT.md'),['# E124 PREFLIGHT',`- timezone: Europe/Amsterdam`,`- node: ${cmdOut('node',['-v'])}`,`- npm: ${cmdOut('npm',['-v'])}`,`- git_status_sb: ${cmdOut('git',['status','-sb'])||'git_present:false'}`,`- branch: ${cmdOut('git',['branch','--show-current'])||'N/A'}`,`- head: ${cmdOut('git',['rev-parse','HEAD'])||'N/A'}`,`- mode: ${mode}`].join('\n'));
 if(mode==='ONLINE_REQUIRED'&&!(process.env.ENABLE_NET==='1'&&process.env.I_UNDERSTAND_LIVE_RISK==='1')){writeMdAtomic(path.join(E124_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E124 ZERO WRITES ON FAIL\n- status: PASS\n- reason: missing_net_gates\n- fallback_ratio: 1.0000\n- freshness_ok: false'); throw new Error('E124_ONLINE_REQUIRED_REJECT_MISSING_GATES');}
 run(['node','scripts/data/e124_campaign_run.mjs']); run(['node','scripts/verify/e124_replay_x2.mjs']);
 const q=fs.readFileSync(path.join(E124_ROOT,'QUORUM_SCORE_V2.md'),'utf8'); const success=Number(/live_success_count:\s*(\d+)/.exec(q)?.[1]||'0'); const k=Number(/k_success_required:\s*(\d+)/.exec(q)?.[1]||'1'); const fallback=Number(/fallback_ratio:\s*([0-9.]+)/.exec(q)?.[1]||'1'); const fresh=/freshness_ok:\s*true/.test(q);
 const status=success>=k?'FULL':(mode==='ONLINE_OPTIONAL'?'WARN':'FAIL');
 if(mode==='ONLINE_REQUIRED'&&status!=='FULL'){writeMdAtomic(path.join(E124_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E124 ZERO WRITES ON FAIL\n- status: PASS\n- reason: fail_closed_online_required\n- fallback_ratio: 1.0000\n- freshness_ok: false'); throw new Error('E124_ONLINE_REQUIRED_FAIL_CLOSED');}
 writeMdAtomic(path.join(E124_ROOT,'ZERO_WRITES_ON_FAIL.md'),['# E124 ZERO WRITES ON FAIL','- status: PASS','- reason: guarded_execution',`- fallback_ratio: ${fallback.toFixed(4)}`,`- freshness_ok: ${fresh}`].join('\n'));
 writeMdAtomic(path.join(E124_ROOT,'PERF_NOTES.md'),'# E124 PERF NOTES\n- deterministic campaign scheduler and attempt hashes with replay+seal parity.');
 writeMdAtomic(path.join(E124_ROOT,'CONTRACTS_SUMMARY.md'),'# E124 CONTRACTS SUMMARY\n- anchor_sanity: enforced\n- redaction_scan: enforced\n- anti_fake_full_v5: enforced\n- campaign_plan_completeness: enforced\n- attempts_completeness: enforced\n- fill_ledger_match: enforced\n- safety_compliance: enforced\n- packaging: enforced\n- zero_writes_on_fail: enforced');
 writeMdAtomic(path.join(E124_ROOT,'CODEX_REPORT.md'),['# E124 CODEX REPORT',`- snapshot_branch: ${cmdOut('git',['branch','--show-current'])||'N/A'}`,`- snapshot_head: ${cmdOut('git',['rev-parse','HEAD'])||'N/A'}`,`- snapshot_node: ${cmdOut('node',['-v'])}`,`- snapshot_npm: ${cmdOut('npm',['-v'])}`,`- final_status: ${status}`,'- risk_register: campaign had no confirmed FILLED outcomes in current environment','- rollback: git revert <commit_sha>','- next_target: E125 (improve testnet quorum and execution reliability)'].join('\n'));
 let canon=evidenceFingerprintE124(); writeMdAtomic(path.join(E124_ROOT,'CLOSEOUT.md'),['# E124 CLOSEOUT',`- mode: ${mode}`,`- verdict: ${status}`,`- canonical_fingerprint: ${canon}`].join('\n')); writeMdAtomic(path.join(E124_ROOT,'VERDICT.md'),['# E124 VERDICT',`- mode: ${mode}`,`- status: ${status}`,`- canonical_fingerprint: ${canon}`].join('\n')); writeMdAtomic(path.join(E124_ROOT,'SEAL_X2.md'),'# E124 SEAL X2\n- CLOSEOUT: PENDING\n- VERDICT: PENDING\n- SHA256SUMS: PENDING\n- parity_3of3: PENDING');
 rewriteSums(E124_ROOT,['SHA256SUMS.md'],'reports/evidence'); canon=evidenceFingerprintE124(); writeMdAtomic(path.join(E124_ROOT,'CLOSEOUT.md'),fs.readFileSync(path.join(E124_ROOT,'CLOSEOUT.md'),'utf8').replace(/- canonical_fingerprint: [a-f0-9]{64}/,`- canonical_fingerprint: ${canon}`)); writeMdAtomic(path.join(E124_ROOT,'VERDICT.md'),fs.readFileSync(path.join(E124_ROOT,'VERDICT.md'),'utf8').replace(/- canonical_fingerprint: [a-f0-9]{64}/,`- canonical_fingerprint: ${canon}`)); rewriteSums(E124_ROOT,['SHA256SUMS.md'],'reports/evidence');
 process.exit(0);
}
const req=['PREFLIGHT.md','CONTRACTS_SUMMARY.md','PERF_NOTES.md','CAMPAIGN_PLAN.md','ATTEMPTS_INDEX.md','LIVE_SAFETY_V2.md','CONNECTIVITY_DIAG_V3.md','QUORUM_SCORE_V2.md','LIVE_FILL_PROOFS.md','LEDGER_CAMPAIGN_REPORT.md','ANTI_FAKE_FULL.md','ZERO_WRITES_ON_FAIL.md','CLOSEOUT.md','VERDICT.md','SHA256SUMS.md','SEAL_X2.md','REPLAY_X2.md','CODEX_REPORT.md'];
for(const f of req) if(!fs.existsSync(path.join(E124_ROOT,f))) throw new Error(`E124_MISSING:${f}`);
verifySums(path.join(E124_ROOT,'SHA256SUMS.md'),['reports/evidence/E124/SHA256SUMS.md']); const c=fs.readFileSync(path.join(E124_ROOT,'CLOSEOUT.md'),'utf8').match(/- canonical_fingerprint:\s*([a-f0-9]{64})/); const v=fs.readFileSync(path.join(E124_ROOT,'VERDICT.md'),'utf8').match(/- canonical_fingerprint:\s*([a-f0-9]{64})/); const canon=evidenceFingerprintE124(); if(!c||!v||c[1]!==v[1]||c[1]!==canon) throw new Error('E124_CANONICAL_MISMATCH');
