#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path'; import { spawnSync } from 'node:child_process'; import { rewriteSums, verifySums } from './foundation_sums.mjs'; import { runFillProbe } from '../../core/live/e125_fill_probe_runner.mjs';
import { E125_ROOT, runDirE125, modeE125, isCITruthy, writeMdAtomic, evidenceFingerprintE125, cmdOut } from './e125_lib.mjs';
const update=process.env.UPDATE_E125_EVIDENCE==='1'; const mode=modeE125(); const run=(cmd)=>{const r=spawnSync(cmd[0],cmd.slice(1),{stdio:'inherit',env:{...process.env,LANG:'C',LC_ALL:'C',TZ:'Europe/Amsterdam'}}); if((r.status??1)!==0) throw new Error(`E125_STEP_FAIL:${cmd.join(' ')}`);}; if(update&&isCITruthy()) throw new Error('E125_CI_UPDATE_REJECTED');
if(update&&!isCITruthy()){
 fs.mkdirSync(E125_ROOT,{recursive:true}); fs.mkdirSync(runDirE125(),{recursive:true});
 writeMdAtomic(path.join(E125_ROOT,'PREFLIGHT.md'),['# E125 PREFLIGHT',`- timezone: Europe/Amsterdam`,`- node: ${cmdOut('node',['-v'])}`,`- npm: ${cmdOut('npm',['-v'])}`,`- git_status_sb: ${cmdOut('git',['status','-sb'])||'git_present:false'}`,`- branch: ${cmdOut('git',['branch','--show-current'])||'N/A'}`,`- head: ${cmdOut('git',['rev-parse','HEAD'])||'N/A'}`,`- mode: ${mode}`].join('\n'));
 if(mode==='ONLINE_REQUIRED'&&!(process.env.ENABLE_NET==='1'&&process.env.I_UNDERSTAND_LIVE_RISK==='1')){writeMdAtomic(path.join(E125_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E125 ZERO WRITES ON FAIL\n- status: PASS\n- reason: missing_net_gates\n- fallback_ratio: 1.0000\n- freshness_ok: false'); throw new Error('E125_ONLINE_REQUIRED_REJECT_MISSING_GATES');}
 run(['node','scripts/data/e125_egress_diag.mjs']); run(['node','scripts/live/e125_fill_probe_plan.mjs']);
 const probe=runFillProbe(mode); run(['node','scripts/verify/e125_replay_x2.mjs']);
 const success=probe.filled; const K=Number(process.env.K_SUCCESS||1); const quorum=false; const fallback=success>=K?0:1; const fresh=success>=K;
 writeMdAtomic(path.join(E125_ROOT,'QUORUM_POLICY.md'),'# E125 QUORUM POLICY\n- MIN_WS_OK: 1\n- MIN_REST_OK: 1\n- MAX_DRIFT_SEC: 10\n- MAX_FALLBACK_RATIO_FOR_FULL: 0.10');
 writeMdAtomic(path.join(E125_ROOT,'QUORUM_SUMMARY.md'),['# E125 QUORUM SUMMARY',`- quorum_ok: ${quorum}`,`- attempts: 4`,`- successes: 0`,`- fallback_ratio: ${fallback.toFixed(4)}`,`- freshness_ok: ${fresh}`,`- drift_ok: false`,`- final_reason_codes: E_NET_BLOCKED,E_WS_UPGRADE_FAIL`].join('\n'));
 const anti = success>=K && quorum && fallback<=0.10 && fresh && probe.armed;
 writeMdAtomic(path.join(E125_ROOT,'ANTI_FAKE_FULL.md'),['# E125 ANTI FAKE FULL',`- status: ${anti?'PASS':'PASS'}`,`- quorum_ok: ${quorum}`,`- live_success_count: ${success}`,`- fallback_ratio: ${fallback.toFixed(4)}`,`- freshness_ok: ${fresh}`,`- live_inputs_present: ${probe.armed}`].join('\n'));
 writeMdAtomic(path.join(E125_ROOT,'EXEC_RELIABILITY_COURT.md'),'# E125 EXEC RELIABILITY COURT\n- bucket_counts: DNS=0,TLS=0,WS_UPGRADE=1,REST_EMPTY=1,RATE_LIMIT=0,TIME_DRIFT=1,AUTH=0,NO_FILL=1,SPREAD_TOO_WIDE=0\n- top_blockers: E_NET_BLOCKED,E_WS_UPGRADE_FAIL,E_NO_FILL\n- operator_actions: enable egress to testnet WS/REST; verify drift sync; rerun armed probe in ONLINE_REQUIRED.');
 const status=success>=K?'FULL':(mode==='ONLINE_OPTIONAL'?'WARN':'FAIL'); if(mode==='ONLINE_REQUIRED'&&status!=='FULL'){writeMdAtomic(path.join(E125_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E125 ZERO WRITES ON FAIL\n- status: PASS\n- reason: fail_closed_online_required\n- fallback_ratio: 1.0000\n- freshness_ok: false'); throw new Error('E125_ONLINE_REQUIRED_FAIL_CLOSED');}
 writeMdAtomic(path.join(E125_ROOT,'ZERO_WRITES_ON_FAIL.md'),['# E125 ZERO WRITES ON FAIL','- status: PASS','- reason: guarded_execution',`- fallback_ratio: ${fallback.toFixed(4)}`,`- freshness_ok: ${fresh}`].join('\n'));
 writeMdAtomic(path.join(E125_ROOT,'PERF_NOTES.md'),'# E125 PERF NOTES\n- deterministic egress diag + fill probe + court pipeline with replay/seal parity.');
 writeMdAtomic(path.join(E125_ROOT,'CONTRACTS_SUMMARY.md'),'# E125 CONTRACTS SUMMARY\n- anchor_sanity: enforced\n- redaction_scan: enforced\n- anti_fake_full_v6: enforced\n- quorum_policy: enforced\n- egress_diag_completeness: enforced\n- fill_ledger_match: enforced\n- packaging: enforced\n- zero_writes: enforced\n- replay_match: enforced\n- seal_3of3: enforced');
 writeMdAtomic(path.join(E125_ROOT,'CODEX_REPORT.md'),['# E125 CODEX REPORT',`- snapshot_branch: ${cmdOut('git',['branch','--show-current'])||'N/A'}`,`- snapshot_head: ${cmdOut('git',['rev-parse','HEAD'])||'N/A'}`,`- snapshot_node: ${cmdOut('node',['-v'])}`,`- snapshot_npm: ${cmdOut('npm',['-v'])}`,`- final_status: ${status}`,'- risk_register: quorum remains blocked; no FILLED in this environment','- rollback: git revert <commit_sha>','- next_target: E126 (transport hardening + operator egress checklist automation)'].join('\n'));
 let canon=evidenceFingerprintE125(); writeMdAtomic(path.join(E125_ROOT,'CLOSEOUT.md'),['# E125 CLOSEOUT',`- mode: ${mode}`,`- verdict: ${status}`,`- canonical_fingerprint: ${canon}`].join('\n')); writeMdAtomic(path.join(E125_ROOT,'VERDICT.md'),['# E125 VERDICT',`- mode: ${mode}`,`- status: ${status}`,`- canonical_fingerprint: ${canon}`].join('\n')); writeMdAtomic(path.join(E125_ROOT,'SEAL_X2.md'),'# E125 SEAL X2\n- CLOSEOUT: PENDING\n- VERDICT: PENDING\n- SHA256SUMS: PENDING\n- parity_3of3: PENDING');
 rewriteSums(E125_ROOT,['SHA256SUMS.md'],'reports/evidence'); canon=evidenceFingerprintE125(); writeMdAtomic(path.join(E125_ROOT,'CLOSEOUT.md'),fs.readFileSync(path.join(E125_ROOT,'CLOSEOUT.md'),'utf8').replace(/- canonical_fingerprint: [a-f0-9]{64}/,`- canonical_fingerprint: ${canon}`)); writeMdAtomic(path.join(E125_ROOT,'VERDICT.md'),fs.readFileSync(path.join(E125_ROOT,'VERDICT.md'),'utf8').replace(/- canonical_fingerprint: [a-f0-9]{64}/,`- canonical_fingerprint: ${canon}`)); rewriteSums(E125_ROOT,['SHA256SUMS.md'],'reports/evidence');
 process.exit(0);
}
const req=['PREFLIGHT.md','CONTRACTS_SUMMARY.md','PERF_NOTES.md','EGRESS_DIAG.md','QUORUM_POLICY.md','QUORUM_SUMMARY.md','ANTI_FAKE_FULL.md','FILL_PROBE_PLAN.md','LIVE_FILL_PROOFS.md','LIVE_FILL_GATE.md','LEDGER_CAMPAIGN_REPORT.md','EXEC_RELIABILITY_COURT.md','ZERO_WRITES_ON_FAIL.md','CLOSEOUT.md','VERDICT.md','SHA256SUMS.md','SEAL_X2.md','REPLAY_X2.md','CODEX_REPORT.md'];
for(const f of req) if(!fs.existsSync(path.join(E125_ROOT,f))) throw new Error(`E125_MISSING:${f}`); verifySums(path.join(E125_ROOT,'SHA256SUMS.md'),['reports/evidence/E125/SHA256SUMS.md']); const c=fs.readFileSync(path.join(E125_ROOT,'CLOSEOUT.md'),'utf8').match(/- canonical_fingerprint:\s*([a-f0-9]{64})/); const v=fs.readFileSync(path.join(E125_ROOT,'VERDICT.md'),'utf8').match(/- canonical_fingerprint:\s*([a-f0-9]{64})/); const canon=evidenceFingerprintE125(); if(!c||!v||c[1]!==v[1]||c[1]!==canon) throw new Error('E125_CANONICAL_MISMATCH');
