#!/usr/bin/env node
import crypto from 'node:crypto'; import { probeTarget, proxyShape } from '../../core/net/transport.mjs'; import { modeE126, writeMdAtomic } from './e126_lib.mjs';
const mode=modeE126(); const enabled=process.env.ENABLE_NET==='1'&&process.env.I_UNDERSTAND_LIVE_RISK==='1'; const force=process.env.FORCE_NET_DOWN==='1';
const targets=[['BYBIT','REST','https://api-testnet.bybit.com/v5/market/time'],['BYBIT','WS','wss://stream-testnet.bybit.com/v5/public/linear'],['BINANCE','REST','https://api.binance.com/api/v3/time'],['BINANCE','WS','wss://stream.binance.com:9443/ws/btcusdt@trade']];
const rows=[]; for(const [p,c,u] of targets){const r = mode==='OFFLINE_ONLY'?{dns_ok:false,tcp_ok:false,tls_ok:false,http_status:'NA',ws_event:false,bytes:0,schema_ok:false,non_empty:false,rtt_ms:0,reason_code:'E_NET_BLOCKED',retries:0,time_drift_sec:'NA'}:await probeTarget({channel:c,enabled,forceNetDown:force}); rows.push({target_id:`${p}-${c}`,provider:p,channel:c,endpoint:u,url_hash:crypto.createHash('sha256').update(u).digest('hex').slice(0,16),...r});}
const pr=proxyShape(process.env.PROXY_URL||'');
writeMdAtomic('reports/evidence/E126/EGRESS_DIAG_V5.md',['# E126 EGRESS DIAG V5',`- mode: ${mode}`,`- proxy_scheme: ${pr.scheme}`,`- proxy_hash: ${pr.hash}`,'| target_id | provider | channel | endpoint | url_hash | dns_ok | tcp_ok | tls_ok | http_status | ws_event | rtt_ms | bytes | schema_ok | non_empty | retries | time_drift_sec | reason_code |','|---|---|---|---|---|---|---|---|---|---|---:|---:|---|---|---:|---:|---|',...rows.map(r=>`| ${r.target_id} | ${r.provider} | ${r.channel} | ${r.endpoint} | ${r.url_hash} | ${r.dns_ok} | ${r.tcp_ok} | ${r.tls_ok} | ${r.http_status} | ${r.ws_event} | ${r.rtt_ms} | ${r.bytes} | ${r.schema_ok} | ${r.non_empty} | ${r.retries} | ${r.time_drift_sec} | ${r.reason_code} |`)].join('\n'));
const wsOk=rows.some(r=>r.channel==='WS'&&r.ws_event); const restOk=rows.some(r=>r.channel==='REST'&&r.non_empty&&r.schema_ok);
if(mode==='ONLINE_REQUIRED'&&(!wsOk||!restOk)) process.exit(1);
