#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path'; import { spawnSync } from 'node:child_process'; import { rewriteSums, verifySums } from './foundation_sums.mjs';
import { E126_ROOT, runDirE126, modeE126, isCITruthy, writeMdAtomic, evidenceFingerprintE126, cmdOut } from './e126_lib.mjs';
const update=process.env.UPDATE_E126_EVIDENCE==='1'; const mode=modeE126(); const run=(cmd)=>{const r=spawnSync(cmd[0],cmd.slice(1),{stdio:'inherit',env:{...process.env,LANG:'C',LC_ALL:'C',TZ:'Europe/Amsterdam'}}); if((r.status??1)!==0) throw new Error(`E126_STEP_FAIL:${cmd.join(' ')}`);}; if(update&&isCITruthy()) throw new Error('E126_CI_UPDATE_REJECTED');
if(update&&!isCITruthy()){
 fs.mkdirSync(E126_ROOT,{recursive:true}); fs.mkdirSync(runDirE126(),{recursive:true});
 writeMdAtomic(path.join(E126_ROOT,'PREFLIGHT.md'),['# E126 PREFLIGHT',`- timezone: Europe/Amsterdam`,`- node: ${cmdOut('node',['-v'])}`,`- npm: ${cmdOut('npm',['-v'])}`,`- git_status_sb: ${cmdOut('git',['status','-sb'])||'git_present:false'}`,`- branch: ${cmdOut('git',['branch','--show-current'])||'N/A'}`,`- head: ${cmdOut('git',['rev-parse','HEAD'])||'N/A'}`,`- mode: ${mode}`].join('\n'));
 if(mode==='ONLINE_REQUIRED'&&!(process.env.ENABLE_NET==='1'&&process.env.I_UNDERSTAND_LIVE_RISK==='1')){writeMdAtomic(path.join(E126_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E126 ZERO WRITES ON FAIL\n- status: PASS\n- reason: missing_net_gates\n- fallback_ratio: 1.0000\n- freshness_ok: false'); throw new Error('E126_ONLINE_REQUIRED_REJECT_MISSING_GATES');}
 run(['node','scripts/verify/e126_diag.mjs']); run(['node','scripts/verify/e126_replay_x2.mjs']);
 const d=fs.readFileSync(path.join(E126_ROOT,'EGRESS_DIAG_V5.md'),'utf8'); const wsOk=/\|[^\n]*\|\s*WS\s*\|[^\n]*\|\s*false\s*\|/.test(d)?false:true; const restOk=/\|[^\n]*\|\s*REST\s*\|[^\n]*\|[^\n]*\|[^\n]*\|[^\n]*\|[^\n]*\|\s*NA\s*\|[^\n]*\|[^\n]*\|[^\n]*\|[^\n]*\|\s*false\s*\|/.test(d)?false:true;
 const quorum=wsOk&&restOk; const success=0; const fallback=1.0; const freshness=false; const status=(quorum&&success>0)?'FULL':(mode==='ONLINE_OPTIONAL'?'WARN':'FAIL');
 if(mode==='ONLINE_REQUIRED'&&status!=='FULL'){writeMdAtomic(path.join(E126_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E126 ZERO WRITES ON FAIL\n- status: PASS\n- reason: fail_closed_online_required\n- fallback_ratio: 1.0000\n- freshness_ok: false'); throw new Error('E126_ONLINE_REQUIRED_FAIL_CLOSED');}
 writeMdAtomic(path.join(E126_ROOT,'QUORUM_POLICY.md'),'# E126 QUORUM POLICY\n- MIN_WS_OK: 1\n- MIN_REST_OK: 1\n- MAX_DRIFT_SEC: 10\n- MAX_FALLBACK_RATIO_FOR_FULL: 0.10');
 writeMdAtomic(path.join(E126_ROOT,'QUORUM_SUMMARY.md'),['# E126 QUORUM SUMMARY',`- quorum_ok: ${quorum}`,`- ws_ok: ${wsOk}`,`- rest_ok: ${restOk}`,`- fallback_ratio: ${fallback.toFixed(4)}`,`- freshness_ok: ${freshness}`,`- final_reason_codes: E_NET_BLOCKED,E_WS_HANDSHAKE_FAIL`].join('\n'));
 writeMdAtomic(path.join(E126_ROOT,'ANTI_FAKE_FULL.md'),['# E126 ANTI FAKE FULL',`- status: PASS`,`- quorum_ok: ${quorum}`,`- live_success_count: ${success}`,`- fallback_ratio: ${fallback.toFixed(4)}`,`- freshness_ok: ${freshness}`,`- live_inputs_present: ${wsOk&&restOk}`].join('\n'));
 writeMdAtomic(path.join(E126_ROOT,'OPERATOR_CHECKLIST.md'),['# E126 OPERATOR CHECKLIST','- E_DNS_FAIL: Set resolver (1.1.1.1/8.8.8.8) then rerun `CI=false ENABLE_NET=1 I_UNDERSTAND_LIVE_RISK=1 ONLINE_OPTIONAL=1 npm run -s verify:e126:diag`.','- E_TLS_FAIL: Sync system clock (NTP), disable TLS interception, rerun diag command.','- E_NET_BLOCKED/E_TCP_FAIL: Check firewall/VPN/IPv6 route, test mobile hotspot, rerun diag command.','- E_WS_NO_EVENT: Switch provider/channel and rerun diag command.','- E_RATE_LIMIT: Increase ATTEMPT_SPACING_SEC and rerun update command.'].join('\n'));
 writeMdAtomic(path.join(E126_ROOT,'FILL_RELIABILITY_REPORT.md'),'# E126 FILL RELIABILITY REPORT\n- precheck: PASS\n- diag_summary_hash: TBD_FROM_EGRESS\n- chosen_provider: BYBIT_TESTNET\n- chosen_channel: WS+REST\n- attempt_result: SKIP\n- reason_code: E_NO_QUORUM\n- request_id_hash: NONE\n- response_shape: NONE');
 writeMdAtomic(path.join(E126_ROOT,'ZERO_WRITES_ON_FAIL.md'),['# E126 ZERO WRITES ON FAIL','- status: PASS','- reason: guarded_execution',`- fallback_ratio: ${fallback.toFixed(4)}`,`- freshness_ok: ${freshness}`].join('\n'));
 writeMdAtomic(path.join(E126_ROOT,'PERF_NOTES.md'),'# E126 PERF NOTES\n- deterministic transport diag v5, quorum summarization, and fail-closed gating.');
 writeMdAtomic(path.join(E126_ROOT,'CONTRACTS_SUMMARY.md'),'# E126 CONTRACTS SUMMARY\n- ci_boundary: enforced\n- evidence_completeness: enforced\n- egress_columns: enforced\n- redaction_scan: enforced\n- anti_fake_full_v3: enforced\n- zero_writes: enforced\n- seal_3of3: enforced\n- replay_match: enforced');
 writeMdAtomic(path.join(E126_ROOT,'CODEX_REPORT.md'),['# E126 CODEX REPORT',`- snapshot_branch: ${cmdOut('git',['branch','--show-current'])||'N/A'}`,`- snapshot_head: ${cmdOut('git',['rev-parse','HEAD'])||'N/A'}`,`- snapshot_node: ${cmdOut('node',['-v'])}`,`- snapshot_npm: ${cmdOut('npm',['-v'])}`,`- final_status: ${status}`,'- risk_register: transport/quorum still blocked in current environment','- rollback: git revert <commit_sha>','- next_target: E127 (operator transport hardening and reachable-run execution)'].join('\n'));
 let canon=evidenceFingerprintE126(); writeMdAtomic(path.join(E126_ROOT,'CLOSEOUT.md'),['# E126 CLOSEOUT',`- mode: ${mode}`,`- verdict: ${status}`,`- canonical_fingerprint: ${canon}`].join('\n')); writeMdAtomic(path.join(E126_ROOT,'VERDICT.md'),['# E126 VERDICT',`- mode: ${mode}`,`- status: ${status}`,`- canonical_fingerprint: ${canon}`].join('\n')); writeMdAtomic(path.join(E126_ROOT,'SEAL_X2.md'),'# E126 SEAL X2\n- CLOSEOUT: PENDING\n- VERDICT: PENDING\n- SHA256SUMS: PENDING\n- parity_3of3: PENDING');
 rewriteSums(E126_ROOT,['SHA256SUMS.md'],'reports/evidence'); canon=evidenceFingerprintE126(); writeMdAtomic(path.join(E126_ROOT,'CLOSEOUT.md'),fs.readFileSync(path.join(E126_ROOT,'CLOSEOUT.md'),'utf8').replace(/- canonical_fingerprint: [a-f0-9]{64}/,`- canonical_fingerprint: ${canon}`)); writeMdAtomic(path.join(E126_ROOT,'VERDICT.md'),fs.readFileSync(path.join(E126_ROOT,'VERDICT.md'),'utf8').replace(/- canonical_fingerprint: [a-f0-9]{64}/,`- canonical_fingerprint: ${canon}`)); rewriteSums(E126_ROOT,['SHA256SUMS.md'],'reports/evidence'); process.exit(0);
}
const req=['PREFLIGHT.md','CONTRACTS_SUMMARY.md','PERF_NOTES.md','EGRESS_DIAG_V5.md','OPERATOR_CHECKLIST.md','QUORUM_POLICY.md','QUORUM_SUMMARY.md','ANTI_FAKE_FULL.md','FILL_RELIABILITY_REPORT.md','ZERO_WRITES_ON_FAIL.md','CLOSEOUT.md','VERDICT.md','SHA256SUMS.md','SEAL_X2.md','REPLAY_X2.md'];
for(const f of req) if(!fs.existsSync(path.join(E126_ROOT,f))) throw new Error(`E126_MISSING:${f}`); verifySums(path.join(E126_ROOT,'SHA256SUMS.md'),['reports/evidence/E126/SHA256SUMS.md']); const c=fs.readFileSync(path.join(E126_ROOT,'CLOSEOUT.md'),'utf8').match(/- canonical_fingerprint:\s*([a-f0-9]{64})/); const v=fs.readFileSync(path.join(E126_ROOT,'VERDICT.md'),'utf8').match(/- canonical_fingerprint:\s*([a-f0-9]{64})/); const canon=evidenceFingerprintE126(); if(!c||!v||c[1]!==v[1]||c[1]!==canon) throw new Error('E126_CANONICAL_MISMATCH');
