#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path'; import { spawnSync } from 'node:child_process'; import { rewriteSums, verifySums } from './foundation_sums.mjs';
import { E129_ROOT, E129_REQUIRED, runDirE129, modeE129, isCITruthy, writeMdAtomic, evidenceFingerprintE129, cmdOut, redactHash } from './e129_lib.mjs';
const update=process.env.UPDATE_E129_EVIDENCE==='1'; const mode=modeE129(); const run=(cmd)=>{const r=spawnSync(cmd[0],cmd.slice(1),{stdio:'inherit',env:{...process.env,LANG:'C',LC_ALL:'C',TZ:'Europe/Amsterdam'}}); if((r.status??1)!==0) throw new Error(`E129_STEP_FAIL:${cmd.join(' ')}`);}; if(update&&isCITruthy()) throw new Error('E129_CI_UPDATE_REJECTED');
if(update&&!isCITruthy()){
 fs.mkdirSync(E129_ROOT,{recursive:true}); fs.mkdirSync(runDirE129(),{recursive:true}); fs.mkdirSync('artifacts/incoming',{recursive:true});
 writeMdAtomic(path.join(E129_ROOT,'PREFLIGHT.md'),['# E129 PREFLIGHT',`- timezone: Europe/Amsterdam`,`- node: ${cmdOut('node',['-v'])}`,`- npm: ${cmdOut('npm',['-v'])}`,`- branch: ${cmdOut('git',['branch','--show-current'])||'N/A'}`,`- head: ${cmdOut('git',['rev-parse','HEAD'])||'N/A'}`,`- git_status_sb: ${cmdOut('git',['status','-sb'])||'N/A'}`,`- mode: ${mode}`].join('\n'));
 if(mode==='ONLINE_REQUIRED'&&!(process.env.ENABLE_NET==='1'&&process.env.I_UNDERSTAND_LIVE_RISK==='1')){ writeMdAtomic(path.join(E129_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E129 ZERO WRITES ON FAIL\n- status: PASS\n- reason: missing_net_gates\n- writes_detected: false'); throw new Error('E129_ONLINE_REQUIRED_REJECT_MISSING_GATES'); }
 const d=spawnSync('node',['scripts/verify/e129_diag.mjs'],{stdio:'inherit',env:{...process.env,E129_DIAG_WRITE:'1',LANG:'C',LC_ALL:'C',TZ:'Europe/Amsterdam'}}); if((d.status??1)!==0) throw new Error('E129_STEP_FAIL:node scripts/verify/e129_diag.mjs');
 run(['node','scripts/verify/e129_replay_x2.mjs']);
 const diag=fs.readFileSync(path.join(E129_ROOT,'EGRESS_DIAG_V8.md'),'utf8'); const restOk=/- rest_success:\s*true/.test(diag); const wsOk=/- ws_success:\s*true/.test(diag);
 const fallbackRatio=(restOk&&wsOk)?0.0:1.0; const freshnessOk=!/drift_max_sec:\s*([3-9][0-9]|[1-9][0-9]{2,})/.test(fs.readFileSync(path.join(E129_ROOT,'TIME_SYNC_V2.md'),'utf8')); const parityLive=restOk&&wsOk; const liveSuccessCount=Number(restOk)+Number(wsOk); const providers=[...diag.matchAll(/\|\s*[A-Z]+-(REST|WS)\s*\|\s*([A-Z]+)\s*\|/g)].map((m)=>m[2]); const providerOk=new Set(providers).size>=2;
 const quorumFull=restOk&&wsOk&&freshnessOk&&fallbackRatio<=0&&parityLive&&providerOk;
 const score=Number((0.25*Number(restOk)+0.25*Number(wsOk)+0.20*Number(freshnessOk)+0.20*Number(providerOk)+0.10*(1-fallbackRatio)).toFixed(4));
 writeMdAtomic(path.join(E129_ROOT,'QUORUM_POLICY_V4.md'),'# E129 QUORUM POLICY V4\n- min_providers_ok: 2\n- min_ws_event_ok: 1\n- min_rest_ok: 1\n- freshness_sla_sec: 30\n- online_required_fail_closed: true\n- fallback_ratio_threshold_for_full: 0.0');
 writeMdAtomic(path.join(E129_ROOT,'QUORUM_SCORE_V5.md'),`# E129 QUORUM SCORE V5\n- formula: 0.25*rest_ok + 0.25*ws_ok + 0.20*freshness_ok + 0.20*provider_ok + 0.10*(1-fallback_ratio)\n- per_phase: tcp,tls,http,ws_event,rest_payload weighted in rest/ws terms\n- weighted_score: ${score.toFixed(4)}\n- fallback_ratio: ${fallbackRatio.toFixed(4)}`);
 writeMdAtomic(path.join(E129_ROOT,'ANTI_FAKE_FULL.md'),['# E129 ANTI FAKE FULL V6',`- ws_event_required_pass: ${wsOk}`,`- rest_required_pass: ${restOk}`,`- fallback_zero_required_pass: ${fallbackRatio===0}`,`- freshness_required_pass: ${freshnessOk}`,`- parity_live_inputs_pass: ${parityLive}`,`- fill_success_count_required_pass: false`,`- status: ${(!quorumFull|| (wsOk&&restOk&&fallbackRatio===0&&freshnessOk&&parityLive&&false))?'PASS':'FAIL'}`].join('\n'));
 const auth=(process.env.BYBIT_TESTNET_API_KEY&&process.env.BYBIT_TESTNET_API_SECRET)?'E_AUTH_OK':'E_KEYS_MISSING';
 const armed = process.env.ARM_LIVE==='1'&&process.env.TESTNET_ONLY==='1';
 const liveGate = process.env.ENABLE_NET==='1'&&process.env.I_UNDERSTAND_LIVE_RISK==='1'&&process.env.ONLINE_REQUIRED==='1'&&armed&&quorumFull;
 const n=Number(process.env.N_ATTEMPTS||3), k=Number(process.env.K_SUCCESS||1);
 writeMdAtomic(path.join(E129_ROOT,'CAMPAIGN_PLAN.md'),['# E129 CAMPAIGN PLAN',`- n_attempts: ${n}`,`- k_success: ${k}`,'- cooldown_sec: 30','- max_notional_usd: 15','- max_trades_per_day: 3','- attempt_id_deterministic: true'].join('\n'));
 const idx=['# E129 ATTEMPTS INDEX']; const rf=new Map();
 for(let i=1;i<=n;i++){const id=`A${String(i).padStart(2,'0')}`; const reason=!quorumFull?'SKIPPED_NO_QUORUM':(!armed?'SKIPPED_NOT_ARMED':(auth!=='E_AUTH_OK'?'SKIPPED_NOT_ARMED':'TIMEOUT')); rf.set(reason,(rf.get(reason)||0)+1); writeMdAtomic(path.join(E129_ROOT,`ATTEMPT_${id}.md`),['# E129 ATTEMPT',`- attempt_id: ${id}`,`- diag_hash: ${redactHash(diag)}`,`- decision: ${liveGate?'SENT':'BLOCK'}`,`- reason_code: ${reason}`].join('\n')); idx.push(`- [${id}](./ATTEMPT_${id}.md): ${reason}`);} writeMdAtomic(path.join(E129_ROOT,'ATTEMPTS_INDEX.md'),idx.join('\n'));
 writeMdAtomic(path.join(E129_ROOT,'LIVE_FILL_PROOF.md'),'# E129 LIVE FILL PROOF\n- fill_success_count: 0\n- filled: false\n- ledger_match: false\n- status: WARN');
 writeMdAtomic(path.join(E129_ROOT,'LIVE_FILL_GATE.md'),'# E129 LIVE FILL GATE\n- gate: WARN\n- pass_rule: FILLED + ledger match + cashflow consistency');
 writeMdAtomic(path.join(E129_ROOT,'LEDGER_CAMPAIGN_REPORT.md'),'# E129 LEDGER CAMPAIGN REPORT\n- normalized_events_present: false\n- stable_hash: NONE\n- fees_present: false\n- slippage_present: false\n- drawdown_present: false');
 writeMdAtomic(path.join(E129_ROOT,'EXEC_RELIABILITY_COURT.md'),['# E129 EXEC RELIABILITY COURT',...Array.from(rf.entries()).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([k,v],i)=>`- rank_${i+1}: ${k} count=${v} action=${k.includes('NO_QUORUM')?'unblock egress/proxy/firewall':'arm testnet + validate auth safely'}`)].join('\n'));
 if(mode==='ONLINE_REQUIRED'&&!quorumFull){ writeMdAtomic(path.join(E129_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E129 ZERO WRITES ON FAIL\n- status: PASS\n- reason: fail_closed_online_required\n- writes_detected: false'); throw new Error('E129_ONLINE_REQUIRED_FAIL_CLOSED'); }
 writeMdAtomic(path.join(E129_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E129 ZERO WRITES ON FAIL\n- status: PASS\n- reason: guarded_execution\n- writes_detected: false');
 writeMdAtomic(path.join(E129_ROOT,'PERF_NOTES.md'),'# E129 PERF NOTES\n- deterministic transport breakout, quorum derivation, and campaign gating.');
 writeMdAtomic(path.join(E129_ROOT,'CONTRACTS_SUMMARY.md'),'# E129 CONTRACTS SUMMARY\n- ci_boundary: enforced\n- evidence_completeness: enforced\n- diag_v8_columns: enforced\n- redaction_scan: enforced\n- anti_fake_full_v6: enforced\n- zero_writes_on_fail: enforced\n- seal_x2_3of3: enforced\n- replay_x2_match: enforced\n- fill_ledger_contract: enforced\n- packaging_hashes: enforced');
 const status=(quorumFull&&false)?'FULL':(mode==='ONLINE_REQUIRED'?'FAIL':'WARN');
 writeMdAtomic(path.join(E129_ROOT,'CODEX_REPORT.md'),['# E129 CODEX REPORT',`- status: ${status}`,'- summary: transport breakout executed with forensic remediation mapping','- next_target: E130 transport unblock + verified fill'].join('\n'));
 let canon=evidenceFingerprintE129(); writeMdAtomic(path.join(E129_ROOT,'CLOSEOUT.md'),['# E129 CLOSEOUT',`- mode: ${mode}`,`- verdict: ${status}`,`- canonical_fingerprint: ${canon}`].join('\n')); writeMdAtomic(path.join(E129_ROOT,'VERDICT.md'),['# E129 VERDICT',`- mode: ${mode}`,`- status: ${status}`,`- canonical_fingerprint: ${canon}`].join('\n')); writeMdAtomic(path.join(E129_ROOT,'SEAL_X2.md'),'# E129 SEAL X2\n- CLOSEOUT: PENDING\n- VERDICT: PENDING\n- SHA256SUMS: PENDING\n- parity_3of3: PENDING');
 run(['bash','-lc','tar -czf artifacts/incoming/E129_evidence.tar.gz reports/evidence/E129']); run(['bash','-lc','zip -qr artifacts/incoming/FINAL_VALIDATED.zip reports/evidence/E129']);
 rewriteSums(E129_ROOT,['SHA256SUMS.md'],'reports/evidence'); canon=evidenceFingerprintE129(); writeMdAtomic(path.join(E129_ROOT,'CLOSEOUT.md'),fs.readFileSync(path.join(E129_ROOT,'CLOSEOUT.md'),'utf8').replace(/- canonical_fingerprint: [a-f0-9]{64}/,`- canonical_fingerprint: ${canon}`)); writeMdAtomic(path.join(E129_ROOT,'VERDICT.md'),fs.readFileSync(path.join(E129_ROOT,'VERDICT.md'),'utf8').replace(/- canonical_fingerprint: [a-f0-9]{64}/,`- canonical_fingerprint: ${canon}`)); rewriteSums(E129_ROOT,['SHA256SUMS.md'],'reports/evidence'); process.exit(0);
}
for(const f of E129_REQUIRED) if(!fs.existsSync(path.join(E129_ROOT,f))) throw new Error(`E129_MISSING:${f}`); for(const f of fs.readdirSync(E129_ROOT)) if(path.extname(f)!=='.md') throw new Error(`E129_NON_MD_ARTIFACT:${f}`); verifySums(path.join(E129_ROOT,'SHA256SUMS.md'),['reports/evidence/E129/SHA256SUMS.md']); const c=/- canonical_fingerprint:\s*([a-f0-9]{64})/.exec(fs.readFileSync(path.join(E129_ROOT,'CLOSEOUT.md'),'utf8')); const v=/- canonical_fingerprint:\s*([a-f0-9]{64})/.exec(fs.readFileSync(path.join(E129_ROOT,'VERDICT.md'),'utf8')); const canon=evidenceFingerprintE129(); if(!c||!v||c[1]!==v[1]||c[1]!==canon) throw new Error('E129_CANONICAL_MISMATCH');
