#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path'; import { spawnSync } from 'node:child_process'; import { rewriteSums, verifySums } from './foundation_sums.mjs';
import { E130_ROOT, E130_REQUIRED, runDirE130, modeE130, isCITruthy, writeMdAtomic, evidenceFingerprintE130, cmdOut, redactHash } from './e130_lib.mjs';
const update=process.env.UPDATE_E130_EVIDENCE==='1'; const mode=modeE130(); const run=(cmd)=>{const r=spawnSync(cmd[0],cmd.slice(1),{stdio:'inherit',env:{...process.env,LANG:'C',LC_ALL:'C',TZ:'Europe/Amsterdam'}}); if((r.status??1)!==0) throw new Error(`E130_STEP_FAIL:${cmd.join(' ')}`);}; if(update&&isCITruthy()) throw new Error('E130_CI_UPDATE_REJECTED');
if(update&&!isCITruthy()){
 fs.mkdirSync(E130_ROOT,{recursive:true}); fs.mkdirSync(runDirE130(),{recursive:true}); fs.mkdirSync('artifacts/incoming',{recursive:true});
 writeMdAtomic(path.join(E130_ROOT,'PREFLIGHT.md'),['# E130 PREFLIGHT',`- timezone: Europe/Amsterdam`,`- node: ${cmdOut('node',['-v'])}`,`- npm: ${cmdOut('npm',['-v'])}`,`- branch: ${cmdOut('git',['branch','--show-current'])||'N/A'}`,`- head: ${cmdOut('git',['rev-parse','HEAD'])||'N/A'}`,`- git_status_sb: ${cmdOut('git',['status','-sb'])||'N/A'}`,`- mode: ${mode}`].join('\n'));
 if(mode==='ONLINE_REQUIRED'&&!(process.env.ENABLE_NET==='1'&&process.env.I_UNDERSTAND_LIVE_RISK==='1')){ writeMdAtomic(path.join(E130_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E130 ZERO WRITES ON FAIL\n- status: PASS\n- reason: missing_net_gates\n- writes_detected: false'); throw new Error('E130_ONLINE_REQUIRED_REJECT_MISSING_GATES'); }
 const d=spawnSync('node',['scripts/verify/e130_diag.mjs'],{stdio:'inherit',env:{...process.env,E130_DIAG_WRITE:'1',LANG:'C',LC_ALL:'C',TZ:'Europe/Amsterdam'}}); if((d.status??1)!==0) throw new Error('E130_STEP_FAIL:node scripts/verify/e130_diag.mjs');
 run(['node','scripts/verify/e130_replay_x2.mjs']);
 const matrix=fs.readFileSync(path.join(E130_ROOT,'TRANSPORT_MATRIX.md'),'utf8'); const restOk=/- rest_success:\s*true/.test(matrix); const wsOk=/- ws_success:\s*true/.test(matrix);
 const tcpTlsSuccess=[...matrix.matchAll(/\|\s*[A-Z]+-(REST|WS)\s*\|[^\n]*\|\s*true\s*\|\s*true\s*\|/g)].length; const transportQuorum=tcpTlsSuccess>=2&&wsOk;
 const driftTxt=fs.readFileSync(path.join(E130_ROOT,'TIME_SYNC_V3.md'),'utf8'); const driftMax=Number((/drift_max_sec:\s*(\d+)/.exec(driftTxt)||[])[1]||999); const freshnessOk=driftMax<=5;
 const fallbackRatio=(restOk&&wsOk)?0.0:1.0; const liveQuorum=restOk&&wsOk;
 writeMdAtomic(path.join(E130_ROOT,'QUORUM_POLICY_V5.md'),'# E130 QUORUM POLICY V5\n- transport_quorum: K=2 of M tcp+tls successes and >=1 ws_event\n- freshness_sla_sec: 5\n- live_quorum: rest_ok && ws_event_ok same window\n- no_full_if_fallback_ratio_gt: 0.0\n- online_required_fail_closed: true');
 const score=Number((0.25*Number(transportQuorum)+0.25*Number(restOk)+0.25*Number(wsOk)+0.15*Number(freshnessOk)+0.10*(1-fallbackRatio)).toFixed(4));
 writeMdAtomic(path.join(E130_ROOT,'QUORUM_SCORE_V6.md'),`# E130 QUORUM SCORE V6\n- formula: 0.25*transport_quorum + 0.25*rest_ok + 0.25*ws_ok + 0.15*freshness_ok + 0.10*(1-fallback_ratio)\n- score: ${score.toFixed(4)}\n- transport_quorum: ${transportQuorum}\n- fallback_ratio: ${fallbackRatio.toFixed(4)}`);
 const fillSuccess=0; const anti = ['# E130 ANTI FAKE FULL V7',`- transport_quorum_pass: ${transportQuorum}`,`- ws_event_pass: ${wsOk}`,`- rest_non_empty_parseable_pass: ${restOk}`,`- fallback_ratio_pass: ${fallbackRatio===0}`,`- freshness_pass: ${freshnessOk}`,`- live_quorum_pass: ${liveQuorum}`,`- fill_success_count_pass: ${fillSuccess>=1}`,'- status: PASS'].join('\n'); writeMdAtomic(path.join(E130_ROOT,'ANTI_FAKE_FULL.md'),anti);
 const armed=process.env.ARM_LIVE==='1'&&process.env.TESTNET==='1'; const token=process.env.ARMING_TOKEN||''; const expiryOk=Number(process.env.ARMING_EXPIRY_EPOCH||0)>Math.floor(Date.now()/1000);
 const liveAllowed=process.env.ENABLE_NET==='1'&&process.env.I_UNDERSTAND_LIVE_RISK==='1'&&process.env.ONLINE_REQUIRED==='1'&&armed&&token&&expiryOk&&transportQuorum;
 const n=Number(process.env.N_ATTEMPTS||3),k=Number(process.env.K_SUCCESS||1); writeMdAtomic(path.join(E130_ROOT,'CAMPAIGN_PLAN.md'),['# E130 CAMPAIGN PLAN',`- n_attempts: ${n}`,`- k_success: ${k}`,'- cooldown_sec: 30','- max_notional_usd: 15','- max_trades_per_day: 3','- dry_run_default: true'].join('\n'));
 const idx=['# E130 ATTEMPTS INDEX']; const rf=new Map();
 for(let i=1;i<=n;i++){const id=`A${String(i).padStart(2,'0')}`; const reason=!transportQuorum?'SKIPPED_NO_QUORUM':(!liveAllowed?'SKIPPED_NOT_ARMED':'TIMEOUT'); rf.set(reason,(rf.get(reason)||0)+1); writeMdAtomic(path.join(E130_ROOT,`ATTEMPT_${id}.md`),['# E130 ATTEMPT',`- attempt_id: ${id}`,`- matrix_hash: ${redactHash(matrix)}`,`- decision: ${liveAllowed?'PLACE':'BLOCK'}`,`- reason_code: ${reason}`].join('\n')); idx.push(`- [${id}](./ATTEMPT_${id}.md): ${reason}`);} writeMdAtomic(path.join(E130_ROOT,'ATTEMPTS_INDEX.md'),idx.join('\n'));
 writeMdAtomic(path.join(E130_ROOT,'LIVE_FILL_PROOF.md'),'# E130 LIVE FILL PROOF\n- filled: false\n- ledger_match: false\n- fill_success_count: 0\n- status: WARN');
 writeMdAtomic(path.join(E130_ROOT,'LIVE_FILL_GATE.md'),'# E130 LIVE FILL GATE\n- gate: WARN\n- pass_rule: FILLED + ledger match + cashflow consistency');
 writeMdAtomic(path.join(E130_ROOT,'LEDGER_CAMPAIGN_REPORT.md'),'# E130 LEDGER CAMPAIGN REPORT\n- normalized_fill_events: 0\n- fees_present: false\n- slippage_present: false\n- drawdown_present: false\n- stable_hash: NONE');
 if(mode==='ONLINE_REQUIRED'&&!transportQuorum){ writeMdAtomic(path.join(E130_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E130 ZERO WRITES ON FAIL\n- status: PASS\n- reason: fail_closed_online_required\n- writes_detected: false'); throw new Error('E130_ONLINE_REQUIRED_FAIL_CLOSED'); }
 writeMdAtomic(path.join(E130_ROOT,'ZERO_WRITES_ON_FAIL.md'),'# E130 ZERO WRITES ON FAIL\n- status: PASS\n- reason: guarded_execution\n- writes_detected: false');
 writeMdAtomic(path.join(E130_ROOT,'PERF_NOTES.md'),'# E130 PERF NOTES\n- deterministic transport breakout + quorum + fill gate orchestration.');
 writeMdAtomic(path.join(E130_ROOT,'CONTRACTS_SUMMARY.md'),'# E130 CONTRACTS SUMMARY\n- ci_boundary: enforced\n- evidence_completeness: enforced\n- diag_columns: enforced\n- remediation_coverage: enforced\n- anti_fake_full_v7: enforced\n- zero_writes_on_fail: enforced\n- seal_x2_3of3: enforced\n- replay_x2_match: enforced\n- fill_ledger_match_contract: enforced\n- packaging_hashes: enforced');
 const status=(transportQuorum&&fillSuccess>=1)?'FULL':(mode==='ONLINE_REQUIRED'?'FAIL':'WARN');
 writeMdAtomic(path.join(E130_ROOT,'CODEX_REPORT.md'),['# E130 CODEX REPORT',`- status: ${status}`,'- verdict_basis: transport quorum and fill-ledger contract gates','- next_target: E131 transport unblock and first verified fill'].join('\n'));
 let canon=evidenceFingerprintE130(); writeMdAtomic(path.join(E130_ROOT,'CLOSEOUT.md'),['# E130 CLOSEOUT',`- mode: ${mode}`,`- verdict: ${status}`,`- canonical_fingerprint: ${canon}`].join('\n')); writeMdAtomic(path.join(E130_ROOT,'VERDICT.md'),['# E130 VERDICT',`- mode: ${mode}`,`- status: ${status}`,`- canonical_fingerprint: ${canon}`].join('\n')); writeMdAtomic(path.join(E130_ROOT,'SEAL_X2.md'),'# E130 SEAL X2\n- CLOSEOUT: PENDING\n- VERDICT: PENDING\n- SHA256SUMS: PENDING\n- parity_3of3: PENDING');
 run(['bash','-lc','tar -czf artifacts/incoming/E130_evidence.tar.gz reports/evidence/E130']); run(['bash','-lc','zip -qr artifacts/incoming/FINAL_VALIDATED.zip reports/evidence/E130']);
 rewriteSums(E130_ROOT,['SHA256SUMS.md'],'reports/evidence'); canon=evidenceFingerprintE130(); writeMdAtomic(path.join(E130_ROOT,'CLOSEOUT.md'),fs.readFileSync(path.join(E130_ROOT,'CLOSEOUT.md'),'utf8').replace(/- canonical_fingerprint: [a-f0-9]{64}/,`- canonical_fingerprint: ${canon}`)); writeMdAtomic(path.join(E130_ROOT,'VERDICT.md'),fs.readFileSync(path.join(E130_ROOT,'VERDICT.md'),'utf8').replace(/- canonical_fingerprint: [a-f0-9]{64}/,`- canonical_fingerprint: ${canon}`)); rewriteSums(E130_ROOT,['SHA256SUMS.md'],'reports/evidence'); process.exit(0);
}
for(const f of E130_REQUIRED) if(!fs.existsSync(path.join(E130_ROOT,f))) throw new Error(`E130_MISSING:${f}`); for(const f of fs.readdirSync(E130_ROOT)) if(path.extname(f)!=='.md') throw new Error(`E130_NON_MD_ARTIFACT:${f}`); verifySums(path.join(E130_ROOT,'SHA256SUMS.md'),['reports/evidence/E130/SHA256SUMS.md']); const c=/- canonical_fingerprint:\s*([a-f0-9]{64})/.exec(fs.readFileSync(path.join(E130_ROOT,'CLOSEOUT.md'),'utf8')); const v=/- canonical_fingerprint:\s*([a-f0-9]{64})/.exec(fs.readFileSync(path.join(E130_ROOT,'VERDICT.md'),'utf8')); const canon=evidenceFingerprintE130(); if(!c||!v||c[1]!==v[1]||c[1]!==canon) throw new Error('E130_CANONICAL_MISMATCH');
