#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { runE77CanaryEval } from '../edge/e77_canary_eval.mjs';
import { E86_ROOT, E86_LOCK_PATH, E86_CANARY_POLICY, E86_THRESHOLD_POLICY, ensureDir, quietLog, minimalLog, demoDailySentinel } from './e86_lib.mjs';
import { writeMd, sha256File } from './e66_lib.mjs';

const update=process.env.UPDATE_E86_EVIDENCE==='1';
if(process.env.CI==='true'&&update) throw new Error('UPDATE_E86_EVIDENCE forbidden in CI');
if(fs.existsSync(E86_LOCK_PATH)&&process.env.CLEAR_E86_LOCK!=='1') throw new Error(`kill-lock active: ${E86_LOCK_PATH}`);
if(process.env.CLEAR_E86_LOCK==='1'&&process.env.CI!=='true') fs.rmSync(E86_LOCK_PATH,{force:true});
function scalar(raw,k,d){return Number((raw.match(new RegExp(`- ${k}:\\s*([0-9.]+)`))||[])[1]??d);}function parsePolicy(){const raw=fs.readFileSync(E86_CANARY_POLICY,'utf8');return{MIN_WINDOWS_STRICT:scalar(raw,'MIN_WINDOWS_STRICT',4),MAX_DRIFT_STRICT:scalar(raw,'MAX_DRIFT_STRICT',0.0045),MAX_INVALID_STRICT:scalar(raw,'MAX_INVALID_STRICT',0.04),MAX_SPREAD_P50_STRICT:scalar(raw,'MAX_SPREAD_P50_STRICT',0.095),MAX_FEE_AVG_STRICT:scalar(raw,'MAX_FEE_AVG_STRICT',6)};}
function readObs(){const t=fs.readFileSync(path.resolve('reports/evidence/E84/EXEC_RECON_OBSERVED_MULTI.md'),'utf8');const reconFp=(t.match(/recon_fingerprint:\s*([a-f0-9]{64})/)||[])[1]||'';const rows=[...t.matchAll(/^\|\s([^|]+)\s\|\s([0-9]+)\s\|\s([0-9.]+)\s\|\s([0-9.]+)\s\|\s([0-9.]+)\s\|\s([0-9.]+)\s\|/gm)].map((m)=>({symbol:m[1].trim(),windows:Number(m[2]),invalid:Number(m[3]),drift:Number(m[4]),spread:Number(m[5]),fee:Number(m[6])}));return{reconFp,rows};}
function decide(input){const p=parsePolicy(),obs=readObs();const calDrift=Number((fs.readFileSync(path.resolve('reports/evidence/E82/CALIBRATION_COURT.md'),'utf8').match(/drift_rate:\s*([0-9.]+)/)||[])[1]||'1');const rows=obs.rows.sort((a,b)=>a.symbol.localeCompare(b.symbol)).map((r)=>{const rs=[];if(r.windows<p.MIN_WINDOWS_STRICT) rs.push('WINDOWS_LT_MIN');if(calDrift>p.MAX_DRIFT_STRICT) rs.push('DRIFT_GT_MAX');if(r.invalid>p.MAX_INVALID_STRICT) rs.push('INVALID_GT_MAX');if(r.spread>p.MAX_SPREAD_P50_STRICT) rs.push('SPREAD_GT_MAX');if(r.fee>p.MAX_FEE_AVG_STRICT) rs.push('FEE_GT_MAX');const strict=rs.length===0;const stage=input==='AUTO'?(strict?'STRICT_1':'BASELINE'):input;return{symbol:r.symbol,stage_decision:stage,promotion:(stage==='STRICT_1'&&strict)?'PASS':'FAIL',reasons:rs.length?rs:['PROMOTED'],recon_windows:r.windows,invalid_row_rate:r.invalid,spread_p50:r.spread,fee_avg:r.fee,calibration_drift_rate:calDrift};});return{rows,reconFp:obs.reconFp,calDrift};}
function once(stage){const d=decide(stage);const tCourt=(fs.readFileSync(path.join(E86_ROOT,'TIGHTENING_COURT.md'),'utf8').match(/tightening_court_fingerprint:\s*([a-f0-9]{64})/)||[])[1]||'';const evalRun=runE77CanaryEval({seed:Number(process.env.SEED||'12345')});const fp=crypto.createHash('sha256').update(JSON.stringify({recon_fingerprint:d.reconFp,demo_daily_sentinel:demoDailySentinel(),threshold_policy_hash:sha256File(E86_THRESHOLD_POLICY),canary_policy_hash:sha256File(E86_CANARY_POLICY),tightening_court_fingerprint:tCourt,stage_decision:d.rows,rows:evalRun.rows})).digest('hex');return {...d,tCourt,fp};}
const stage=String(process.env.CANARY_STAGE||'AUTO').toUpperCase();if(!['AUTO','BASELINE','STRICT_1'].includes(stage)) throw new Error('CANARY_STAGE must be AUTO|BASELINE|STRICT_1');
const r1=once(stage),r2=once(stage),ok=r1.fp===r2.fp;
if(!ok||process.env.FORCE_E86_MISMATCH==='1'){ensureDir(path.dirname(E86_LOCK_PATH));writeMd(E86_LOCK_PATH,['# E86 KILL LOCK','- reason: DETERMINISTIC_MISMATCH',`- run1_fingerprint: ${r1.fp}`,`- run2_fingerprint: ${r2.fp}`].join('\n'));throw new Error('verify:edge:canary:x2:e86 FAILED');}
if(update&&process.env.CI!=='true'){ensureDir(E86_ROOT);const lines=['# E86 RUNS EDGE CANARY X2',`- canary_stage: ${stage}`,`- run1_fingerprint: ${r1.fp}`,`- run2_fingerprint: ${r2.fp}`,'- deterministic_match: true',`- demo_daily_sentinel: ${demoDailySentinel()}`,`- tightening_court_fingerprint: ${r1.tCourt}`,`- threshold_policy_hash: ${sha256File(E86_THRESHOLD_POLICY)}`,`- canary_policy_hash: ${sha256File(E86_CANARY_POLICY)}`,'','| symbol | stage_decision | promotion | reason_codes | recon_windows | invalid_row_rate | spread_p50 | fee_avg | calibration_drift_rate |','|---|---|---|---|---:|---:|---:|---:|---:|'];for(const d of r1.rows) lines.push(`| ${d.symbol} | ${d.stage_decision} | ${d.promotion} | ${d.reasons.join(',')} | ${d.recon_windows} | ${d.invalid_row_rate.toFixed(8)} | ${d.spread_p50.toFixed(6)} | ${d.fee_avg.toFixed(6)} | ${d.calibration_drift_rate.toFixed(8)} |`);lines.push('','## PROMOTION_READINESS');for(const d of r1.rows) lines.push(`- ${d.symbol}: ${d.promotion} (${d.reasons.join(',')})`);writeMd(path.join(E86_ROOT,'RUNS_EDGE_CANARY_X2.md'),lines.join('\n'));}
quietLog(JSON.stringify({deterministic_match:true,run_fingerprint:r1.fp},null,2));minimalLog(`verify:edge:canary:x2:e86 PASSED run_fingerprint=${r1.fp}`);
