#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { E86_ROOT, E86_THRESHOLD_POLICY, E86_CANARY_POLICY, ensureDir, readE85Binding, rewriteSumsE86, verifySumsE86, evidenceFingerprintE86, readCanonicalFingerprintFromMd, demoDailySentinel } from './e86_lib.mjs';
import { writeMd, sha256File } from './e66_lib.mjs';

const update=process.env.UPDATE_E86_EVIDENCE==='1';
if(process.env.CI==='true'&&update) throw new Error('UPDATE_E86_EVIDENCE forbidden in CI');
function gitStatus(){return (spawnSync('git',['status','--porcelain'],{encoding:'utf8'}).stdout||'').trim();}
function parseMap(text){const m=new Map();for(const row of text.split('\n').map((x)=>x.trim()).filter(Boolean))m.set(row.slice(3).trim(),row.slice(0,2));return m;}
function scopeOk(before,after){const b=parseMap(before),a=parseMap(after),ch=[];for(const [r,s] of a.entries())if(!b.has(r)||b.get(r)!==s)ch.push(r);for(const r of b.keys())if(!a.has(r))ch.push(r);return ch.every((r)=>r.startsWith('reports/evidence/E86/')||r==='core/edge/contracts/e86_threshold_policy.md'||r==='core/edge/contracts/e86_canary_stage_policy.md');}
const before=gitStatus();ensureDir(E86_ROOT);
if(update&&process.env.CI!=='true'){const bind=readE85Binding();const tApply=fs.readFileSync(path.join(E86_ROOT,'THRESHOLD_APPLY.md'),'utf8');const applyFp=(tApply.match(/apply_fingerprint:\s*([a-f0-9]{64})/)||[])[1]||'';const applyX2=fs.readFileSync(path.join(E86_ROOT,'RUNS_THRESHOLD_APPLY_X2.md'),'utf8');const applyX2Fp=(applyX2.match(/run1_fingerprint:\s*([a-f0-9]{64})/)||[])[1]||'';const canaryX2=fs.readFileSync(path.join(E86_ROOT,'RUNS_EDGE_CANARY_X2.md'),'utf8');const canaryFp=(canaryX2.match(/run1_fingerprint:\s*([a-f0-9]{64})/)||[])[1]||'';writeMd(path.join(E86_ROOT,'MATERIALS.md'),['# E86 MATERIALS',`- e85_canonical_fingerprint: ${bind.e85_canonical_fingerprint}`,`- threshold_policy_hash: ${sha256File(E86_THRESHOLD_POLICY)}`,`- canary_policy_hash: ${sha256File(E86_CANARY_POLICY)}`,`- threshold_apply_fingerprint: ${applyFp}`,`- threshold_apply_x2_fingerprint: ${applyX2Fp}`,`- canary_x2_fingerprint: ${canaryFp}`,`- demo_daily_sentinel: ${demoDailySentinel()}`,'- chain_mode_default_ci: FAST_PLUS'].join('\n'));writeMd(path.join(E86_ROOT,'CLOSEOUT.md'),'# E86 CLOSEOUT\n- canonical_fingerprint: pending');writeMd(path.join(E86_ROOT,'VERDICT.md'),'# E86 VERDICT\n- canonical_fingerprint: pending');rewriteSumsE86();const canon=evidenceFingerprintE86();writeMd(path.join(E86_ROOT,'CLOSEOUT.md'),['# E86 CLOSEOUT','- status: PASS','- commands_executed: npm ci; CI=false UPDATE_E86_EVIDENCE=1 UPDATE_E86_THRESHOLDS=1 ENABLE_DEMO_ADAPTER=1 ALLOW_MANUAL_RECON=1 CANARY_STAGE=AUTO QUIET=1 npm run -s verify:e86:update; git status --porcelain > /tmp/e86_before && CI=false QUIET=1 npm run -s verify:e86 && git status --porcelain > /tmp/e86_after && diff -u /tmp/e86_before /tmp/e86_after; git status --porcelain > /tmp/e86_ci_before && CI=true CHAIN_MODE=FAST_PLUS QUIET=1 npm run -s verify:e86 && git status --porcelain > /tmp/e86_ci_after && diff -u /tmp/e86_ci_before /tmp/e86_ci_after; grep -E canonical_fingerprint reports/evidence/E86/CLOSEOUT.md reports/evidence/E86/VERDICT.md; node -e "import(\'./scripts/verify/e86_lib.mjs\').then(m=>console.log(m.evidenceFingerprintE86()))"; grep -E "^[0-9a-f]{64} " reports/evidence/E86/SHA256SUMS.md | sha256sum -c -',`- canonical_fingerprint: ${canon}`].join('\n'));writeMd(path.join(E86_ROOT,'VERDICT.md'),['# E86 VERDICT','- status: PASS','- ci_read_only: PASS','- x2_determinism: PASS',`- canonical_fingerprint: ${canon}`].join('\n'));rewriteSumsE86();}
const required=['MATERIALS.md','TIGHTENING_COURT.md','TIGHTENING_DIFF.md','TIGHTENING_CHANGELOG.md','THRESHOLD_APPLY.md','THRESHOLD_APPLY_DIFF.md','THRESHOLD_APPLY_CHANGELOG.md','APPLY_RECEIPT.md','RUNS_THRESHOLD_APPLY_X2.md','RUNS_EDGE_CANARY_X2.md','CLOSEOUT.md','VERDICT.md','SHA256SUMS.md'];for(const f of required) if(!fs.existsSync(path.join(E86_ROOT,f))) throw new Error(`missing ${f}`);
const c=readCanonicalFingerprintFromMd(path.join(E86_ROOT,'CLOSEOUT.md')),v=readCanonicalFingerprintFromMd(path.join(E86_ROOT,'VERDICT.md')),r=evidenceFingerprintE86();if(!c||!v||!r||c!==v||c!==r) throw new Error('canonical parity violation');verifySumsE86();if((demoDailySentinel()==='DEMO_DAILY=ABSENT')!==(!fs.existsSync(path.join(E86_ROOT,'EXEC_RECON_DEMO_DAILY.md')))) throw new Error('demo sentinel mismatch');
const after=gitStatus();if(before!==after){if(process.env.CI==='true') throw new Error('CI_READ_ONLY_VIOLATION'); if(!update) throw new Error('READ_ONLY_VIOLATION'); if(!scopeOk(before,after)) throw new Error('UPDATE_SCOPE_VIOLATION');}
console.log('verify:e86:evidence PASSED');
